spring.datasource.url=jdbc:postgresql://localhost:5432/eduassist
spring.datasource.username=postgres
spring.datasource.password=W@ss1m1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


